version: '3'
networks:
  elastic:

services:
  es01:
    image: elasticsearch:7.16.3
    container_name: my_es01
    environment:
      - node.name=my_es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /Users/wuyan/data/docker/volumes/elasticsearch/data:/elastic-data
    ports:
      - 9200:9200
    networks:
      - elastic