version: '3'
services:
  #服务名称
  rabbitmq:
    #容器名称
    container_name: my_rabbitmq
    #镜像名称
    image: rabbitmq:latest
    #总是重启后启动
    #restart: "no"
    #端口映射
    ports:
      - 5672:5672
      - 15672:15672
    #挂载k
    # volumes:
    #   - ./data:/var/lib/rabbitmq
    #环境变量
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
