version: "3"
services:
  db:
    image: "postgres:latest"
    container_name: "my_postgres"
    restart: always
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
volumes:
  my_dbdata: