version: '2'
services:
    redis:
      image: "redis:latest"
      container_name: "my_redis"
      command: redis-server
      ports:
        - "63790:6379"
      volumes:
        - my_dbdata:/var/lib/redis/data
volumes:
  my_dbdata:
